

const char threeLetterList[3440][4] = {
    "aab", "aac", "aad", "aae", "aal", "aam", "aan", "aap", "aat", "abd",
    "abe", "abl", "abo", "abr", "abu", "aca", "acc", "ace", "ach", "aci",
    "ack", "acl", "aco", "acr", "acu", "acy", "ada", "adb", "adc", "add",
    "ade", "adf", "adg", "adh", "adi", "adl", "adm", "adn", "ado", "adp",
    "adq", "adr", "ads", "adt", "adu", "adv", "adw", "ady", "adz", "ael",
    "aem", "aen", "aep", "aes", "aev", "aex", "afa", "afe", "aff", "afl",
    "afo", "afr", "afu", "age", "agi", "agm", "ago", "agr", "aha", "ahe",
    "ahi", "aho", "ahy", "ail", "aim", "ain", "air", "ais", "ake", "ala",
    "alb", "alc", "ald", "ale", "alf", "alg", "alh", "ali", "all", "alm",
    "aln", "alo", "alp", "alq", "alr", "als", "alt", "alu", "alv", "alw",
    "alz", "ama", "amb", "amc", "amd", "ame", "amf", "amg", "amh", "ami",
    "aml", "amm", "amn", "amo", "amp", "amq", "amr", "ams", "amt", "amu",
    "amv", "amw", "amz", "ana", "anc", "ane", "ang", "ani", "ano", "ant",
    "aob", "aop", "apa", "ape", "aph", "api", "apl", "apo", "app", "apr",
    "aps", "apu", "aqu", "ara", "ard", "are", "aro", "art", "asa", "asc",
    "ase", "ask", "asl", "asm", "aso", "ass", "ast", "asu", "asw", "asy",
    "ata", "atc", "ate", "ath", "ati", "ato", "atr", "att", "atu", "auc",
    "aul", "aun", "aus", "ave", "avi", "avo", "awa", "awb", "awc", "awd",
    "awe", "awf", "awg", "awh", "awi", "awl", "awm", "awn", "awo", "awp",
    "awq", "awr", "aws", "awt", "awu", "awv", "aww", "awz", "aze", 
    "bdo", "bel", "ber", "bit", "bla", "ble", "bli", "bol", "bor", "bos",
    "bot", "bra", "bri", "bse", "bso", "buc", "bur", "bus", "but", 
    "cab", "cac", "cad", "cae", "cal", "cam", "can", "cap", "car", "cat",
    "cau", "cbl", "cbo", "cbu", "cca", "cce", "cch", "cci", "ccl", "cco",
    "ccr", "ccu", "cde", "cdi", "cdo", "cdy", "cea", "ceb", "cec", "ced",
    "cee", "cef", "ceg", "ceh", "cei", "cel", "cem", "cen", "ceo", "cep",
    "ceq", "cer", "ces", "cet", "ceu", "cev", "cew", "cex", "cez", "cfa",
    "cfe", "cfl", "cfo", "cfr", "cfu", "cgo", "cgr", "cha", "chb", "chc",
    "chd", "che", "chf", "chg", "chh", "chi", "chl", "chm", "chn", "cho",
    "chp", "chq", "chr", "chs", "cht", "chu", "chv", "chw", "chy", "chz",
    "cid", "cim", "cin", "cip", "cir", "cis", "cka", "ckb", "ckc", "ckd",
    "cke", "ckf", "ckg", "ckh", "cki", "ckl", "ckm", "ckn", "cko", "ckp",
    "ckq", "ckr", "cks", "ckt", "cku", "ckv", "ckw", "ckz", "cla", "cle",
    "cli", "clu", "cma", "cme", "cmi", "cmo", "cne", "cno", "cob", "cod",
    "col", "com", "con", "cop", "cor", "coy", "cpa", "cpe", "cph", "cpi",
    "cpl", "cpo", "cpr", "cps", "cpu", "cqu", "cra", "cre", "cri", "cro",
    "cry", "csa", "csc", "cse", "csk", "csl", "csm", "cso", "cst", "csu",
    "csw", "csy", "cta", "ctb", "ctc", "ctd", "cte", "ctf", "ctg", "cth",
    "cti", "ctl", "ctm", "ctn", "cto", "ctp", "ctq", "ctr", "cts", "ctt",
    "ctu", "ctv", "ctw", "ctz", "cui", "cul", "cum", "cun", "cup", "cur",
    "cut", "cve", "cvi", "cvo", "cwa", "cwe", "cwi", "cwo", "cya", "cyb",
    "cyc", "cyd", "cye", "cyf", "cyg", "cyh", "cyi", "cyl", "cym", "cyn",
    "cyo", "cyp", "cyq", "cyr", "cys", "cyt", "cyu", "cyv", "cyw", "cyz",
    "cze", 
    "dab", "dac", "dad", "dae", "dal", "dam", "dan", "dap", "dat", "dbl",
    "dbo", "dbu", "dca", "dce", "dch", "dci", "dcl", "dco", "dcr", "dcu",
    "dde", "ddi", "ddo", "ddy", "dea", "deb", "dec", "ded", "dee", "def",
    "deg", "deh", "dei", "del", "dem", "den", "deo", "dep", "deq", "der",
    "des", "det", "deu", "dev", "dew", "dex", "dez", "dfa", "dfe", "dfl",
    "dfo", "dfr", "dfu", "dgo", "dgr", "dha", "dhe", "dhi", "dho", "dhy",
    "dib", "dic", "dim", "din", "dis", "div", "dla", "dle", "dlu", "dma",
    "dme", "dmi", "dmo", "dne", "dno", "dob", "dom", "doo", "dop", "dor",
    "dot", "dox", "dpa", "dpe", "dph", "dpi", "dpl", "dpo", "dpr", "dps",
    "dpu", "dqu", "dra", "dre", "dro", "dsa", "dsb", "dsc", "dsd", "dse",
    "dsf", "dsg", "dsh", "dsi", "dsk", "dsl", "dsm", "dsn", "dso", "dsp",
    "dsq", "dsr", "dss", "dst", "dsu", "dsv", "dsw", "dsy", "dsz", "dta",
    "dte", "dth", "dto", "dtr", "dtu", "duc", "dul", "dun", "dve", "dvi",
    "dvo", "dwa", "dwe", "dwi", "dwo", "dya", "dyb", "dyc", "dyd", "dye",
    "dyf", "dyg", "dyh", "dyi", "dyl", "dym", "dyn", "dyo", "dyp", "dyq",
    "dyr", "dys", "dyt", "dyu", "dyv", "dyw", "dyz", "dze", 
    "eab", "eac", "ead", "eae", "eal", "eam", "ean", "eap", "eat", "eau",
    "ebl", "ebo", "ebr", "ebu", "eca", "ecd", "ece", "ech", "eci", "ecl",
    "eco", "ecr", "ect", "ecu", "eda", "edb", "edc", "edd", "ede", "edf",
    "edg", "edh", "edi", "edl", "edm", "edn", "edo", "edp", "edq", "edr",
    "eds", "edt", "edu", "edv", "edw", "edy", "edz", "eed", "eel", "eem",
    "een", "eep", "eer", "eev", "eex", "efa", "efe", "efl", "efo", "efr",
    "efu", "ega", "ege", "egl", "ego", "egr", "eha", "ehe", "ehi", "eho",
    "ehy", "eim", "ein", "ela", "elb", "elc", "eld", "ele", "elf", "elg",
    "elh", "eli", "ell", "elm", "eln", "elo", "elp", "elq", "elr", "els",
    "elt", "elu", "elv", "elw", "elz", "ema", "emb", "emc", "emd", "eme",
    "emf", "emg", "emh", "emi", "eml", "emm", "emn", "emo", "emp", "emq",
    "emr", "ems", "emt", "emu", "emv", "emw", "emz", "ena", "enb", "enc",
    "end", "ene", "enf", "eng", "enh", "eni", "enl", "enm", "enn", "eno",
    "enp", "enq", "enr", "ens", "ent", "enu", "env", "enw", "enz", "eob",
    "eop", "epa", "epe", "eph", "epi", "epl", "epo", "epr", "eps", "ept",
    "epu", "equ", "era", "erb", "erc", "erd", "ere", "erf", "erg", "erh",
    "eri", "erl", "erm", "ern", "ero", "erp", "erq", "err", "ers", "ert",
    "eru", "erv", "erw", "ery", "erz", "esa", "esc", "ese", "esi", "esk",
    "esl", "esm", "eso", "ess", "est", "esu", "esw", "esy", "eta", "etb",
    "etc", "etd", "ete", "etf", "etg", "eth", "eti", "etl", "etm", "etn",
    "eto", "etp", "etq", "etr", "ets", "ett", "etu", "etv", "etw", "etz",
    "eul", "eun", "eut", "eve", "evi", "evo", "ewa", "ewe", "ewi", "ewo",
    "exa", "exo", "ext", "eze", 
    "fab", "fac", "fad", "fae", "fal", "fam", "fan", "fap", "far", "fat",
    "fau", "fbl", "fbo", "fbu", "fca", "fce", "fch", "fci", "fcl", "fco",
    "fcr", "fcu", "fde", "fdi", "fdo", "fdy", "fel", "fem", "fen", "fep",
    "fev", "fex", "ffa", "ffe", "ffl", "ffo", "ffr", "ffu", "fgo", "fgr",
    "fha", "fhe", "fhi", "fho", "fhy", "fim", "fin", "fla", "fle", "flu",
    "fma", "fme", "fmi", "fmo", "fne", "fno", "fob", "fol", "fop", "for",
    "fou", "fpa", "fpe", "fph", "fpi", "fpl", "fpo", "fpr", "fps", "fpu",
    "fqu", "fra", "fre", "fro", "fsa", "fsc", "fse", "fsk", "fsl", "fsm",
    "fso", "fst", "fsu", "fsw", "fsy", "fta", "fte", "fth", "fto", "ftr",
    "ftu", "ftw", "ful", "fun", "fur", "fut", "fve", "fvi", "fvo", "fwa",
    "fwe", "fwi", "fwo", "fze", 
    "gab", "gac", "gad", "gae", "gal", "gam", "gan", "gap", "gat", "gbl",
    "gbo", "gbu", "gca", "gce", "gch", "gci", "gcl", "gco", "gcr", "gcu",
    "gde", "gdi", "gdo", "gdy", "gea", "geb", "gec", "ged", "gee", "gef",
    "geg", "geh", "gei", "gel", "gem", "gen", "geo", "gep", "geq", "ger",
    "ges", "get", "geu", "gev", "gew", "gex", "gez", "gfa", "gfe", "gfl",
    "gfo", "gfr", "gfu", "ggo", "ggr", "gha", "ghe", "ghi", "gho", "ght",
    "ghy", "gia", "gic", "gim", "gin", "gla", "gle", "gli", "glu", "gma",
    "gme", "gmi", "gmo", "gne", "gno", "goa", "gob", "goc", "god", "goe",
    "gof", "gog", "goh", "goi", "gol", "gom", "gon", "goo", "gop", "goq",
    "gor", "gos", "got", "gou", "gov", "gow", "goz", "gpa", "gpe", "gph",
    "gpi", "gpl", "gpo", "gpr", "gps", "gpu", "gqu", "gra", "gre", "gro",
    "gru", "gsa", "gsc", "gse", "gsk", "gsl", "gsm", "gso", "gst", "gsu",
    "gsw", "gsy", "gta", "gte", "gth", "gto", "gtr", "gtu", "gua", "gue",
    "gul", "gun", "gve", "gvi", "gvo", "gwa", "gwe", "gwi", "gwo", "gze", 
    "hab", "hac", "had", "hae", "hai", "hal", "ham", "han", "hap", "has",
    "hat", "hbl", "hbo", "hbu", "hca", "hce", "hch", "hci", "hcl", "hco",
    "hcr", "hcu", "hde", "hdi", "hdo", "hdr", "hdy", "hea", "heb", "hec",
    "hed", "hee", "hef", "heg", "heh", "hei", "hel", "hem", "hen", "heo",
    "hep", "heq", "her", "hes", "het", "heu", "hev", "hew", "hex", "hez",
    "hfa", "hfe", "hfl", "hfo", "hfr", "hfu", "hgo", "hgr", "hha", "hhe",
    "hhi", "hho", "hhy", "hib", "him", "hin", "hip", "hla", "hle", "hlu",
    "hma", "hme", "hmi", "hmo", "hne", "hno", "hob", "hon", "hop", "hos",
    "hou", "hpa", "hpe", "hph", "hpi", "hpl", "hpo", "hpr", "hps", "hpu",
    "hqu", "hre", "hro", "hsa", "hsc", "hse", "hsk", "hsl", "hsm", "hso",
    "hst", "hsu", "hsw", "hsy", "hta", "htb", "htc", "htd", "hte", "htf",
    "htg", "hth", "hti", "htl", "htm", "htn", "hto", "htp", "htq", "htr",
    "hts", "htt", "htu", "htv", "htw", "htz", "hul", "hun", "hve", "hvi",
    "hvo", "hwa", "hwe", "hwi", "hwo", "hya", "hyb", "hyc", "hyd", "hye",
    "hyf", "hyg", "hyh", "hyi", "hyl", "hym", "hyn", "hyo", "hyp", "hyq",
    "hyr", "hys", "hyt", "hyu", "hyv", "hyw", "hyz", "hze", 
    "iaa", "iab", "iac", "iad", "iae", "iaf", "iag", "iah", "iai", "ial",
    "iam", "ian", "iao", "iap", "iaq", "iar", "ias", "iat", "iau", "iav",
    "iaw", "iaz", "ibi", "ibl", "ibr", "ica", "icb", "icc", "icd", "ice",
    "icf", "icg", "ich", "ici", "ick", "icl", "icm", "icn", "ico", "icp",
    "icq", "icr", "ics", "ict", "icu", "icv", "icw", "icz", "ida", "idb",
    "idc", "idd", "ide", "idf", "idg", "idh", "idi", "idl", "idm", "idn",
    "ido", "idp", "idq", "idr", "ids", "idt", "idu", "idv", "idw", "idz",
    "iga", "ige", "igm", "igo", "igr", "ila", "ilb", "ilc", "ild", "ile",
    "ilf", "ilg", "ilh", "ili", "ill", "ilm", "iln", "ilo", "ilp", "ilq",
    "ilr", "ils", "ilt", "ilu", "ilv", "ilw", "ilz", "ima", "imp", "ina",
    "inb", "inc", "ind", "ine", "inf", "ing", "inh", "ini", "inl", "inm",
    "inn", "ino", "inp", "inq", "inr", "ins", "int", "inu", "inv", "inw",
    "inz", "ion", "ipa", "ipb", "ipc", "ipd", "ipe", "ipf", "ipg", "iph",
    "ipi", "ipl", "ipm", "ipn", "ipo", "ipp", "ipq", "ipr", "ips", "ipt",
    "ipu", "ipv", "ipw", "ipz", "iqu", "irc", "irl", "isa", "isb", "isc",
    "isd", "ise", "isf", "isg", "ish", "isi", "isl", "ism", "isn", "iso",
    "isp", "isq", "isr", "iss", "ist", "isu", "isv", "isw", "isz", "ita",
    "ith", "iti", "ito", "ity", "iva", "ive", "ivi", 
    "kab", "kac", "kad", "kae", "kal", "kam", "kan", "kap", "kat", "kbl",
    "kbo", "kbu", "kca", "kce", "kch", "kci", "kcl", "kco", "kcr", "kcu",
    "kde", "kdi", "kdo", "kdy", "kea", "keb", "kec", "ked", "kee", "kef",
    "keg", "keh", "kei", "kel", "kem", "ken", "keo", "kep", "keq", "ker",
    "kes", "ket", "keu", "kev", "kew", "kex", "kez", "kfa", "kfe", "kfl",
    "kfo", "kfr", "kfu", "kgo", "kgr", "kha", "khe", "khi", "kho", "khy",
    "kim", "kin", "kla", "kle", "klu", "kma", "kme", "kmi", "kmo", "kne",
    "kno", "kob", "kop", "kou", "kpa", "kpe", "kph", "kpi", "kpl", "kpo",
    "kpr", "kps", "kpu", "kqu", "kre", "kro", "ksa", "ksc", "kse", "ksk",
    "ksl", "ksm", "kso", "kst", "ksu", "ksw", "ksy", "kta", "kte", "kth",
    "kto", "ktr", "ktu", "kul", "kun", "kve", "kvi", "kvo", "kwa", "kwe",
    "kwi", "kwo", "kze", 
    "lab", "lac", "lad", "lae", "lag", "lak", "lal", "lam", "lan", "lap",
    "las", "lat", "lav", "lbl", "lbo", "lbu", "lca", "lce", "lch", "lci",
    "lcl", "lco", "lcr", "lcu", "lde", "ldi", "ldo", "ldy", "lea", "leb",
    "lec", "led", "lee", "lef", "leg", "leh", "lei", "lel", "lem", "len",
    "leo", "lep", "leq", "ler", "les", "let", "leu", "lev", "lew", "lex",
    "lez", "lfa", "lfe", "lfl", "lfo", "lfr", "lfu", "lgi", "lgo", "lgr",
    "lha", "lhe", "lhi", "lho", "lhy", "lib", "lic", "lig", "lim", "lin",
    "liq", "lla", "llb", "llc", "lld", "lle", "llf", "llg", "llh", "lli",
    "lll", "llm", "lln", "llo", "llp", "llq", "llr", "lls", "llt", "llu",
    "llv", "llw", "llz", "lma", "lme", "lmi", "lmo", "lne", "lno", "lob",
    "log", "loo", "lop", "loq", "lou", "low", "lpa", "lpe", "lph", "lpi",
    "lpl", "lpo", "lpr", "lps", "lpu", "lqu", "lre", "lro", "lsa", "lsc",
    "lse", "lsk", "lsl", "lsm", "lso", "lst", "lsu", "lsw", "lsy", "lta",
    "ltb", "ltc", "ltd", "lte", "ltf", "ltg", "lth", "lti", "ltl", "ltm",
    "ltn", "lto", "ltp", "ltq", "ltr", "lts", "ltt", "ltu", "ltv", "ltw",
    "ltz", "luc", "lul", "lun", "lur", "lut", "lve", "lvi", "lvo", "lwa",
    "lwe", "lwi", "lwo", "lya", "lyb", "lyc", "lyd", "lye", "lyf", "lyg",
    "lyh", "lyi", "lyl", "lym", "lyn", "lyo", "lyp", "lyq", "lyr", "lys",
    "lyt", "lyu", "lyv", "lyw", "lyz", "lze", 
    "maa", "mab", "mac", "mad", "mae", "maf", "mag", "mah", "mai", "mal",
    "mam", "man", "mao", "map", "maq", "mar", "mas", "mat", "mau", "mav",
    "maw", "maz", "mbl", "mbo", "mbu", "mca", "mce", "mch", "mci", "mcl",
    "mco", "mcr", "mcu", "mde", "mdi", "mdo", "mdy", "mea", "med", "mel",
    "mem", "men", "mep", "mer", "mev", "mex", "mfa", "mfe", "mfl", "mfo",
    "mfr", "mfu", "mgo", "mgr", "mha", "mhe", "mhi", "mho", "mhy", "mic",
    "mim", "min", "mla", "mle", "mlu", "mma", "mme", "mmi", "mmo", "mne",
    "mno", "mob", "mod", "mok", "mom", "mon", "mop", "mor", "mou", "mpa",
    "mpe", "mph", "mpi", "mpl", "mpo", "mpr", "mps", "mpu", "mqu", "mre",
    "mro", "msa", "msc", "mse", "msk", "msl", "msm", "mso", "mst", "msu",
    "msw", "msy", "mta", "mte", "mth", "mto", "mtr", "mtu", "mul", "mun",
    "mve", "mvi", "mvo", "mwa", "mwe", "mwi", "mwo", "mze", 
    "nab", "nac", "nad", "nae", "nai", "nal", "nam", "nan", "nap", "nat",
    "nbl", "nbo", "nbu", "nca", "nce", "nch", "nci", "ncl", "nco", "ncr",
    "ncu", "nda", "ndb", "ndc", "ndd", "nde", "ndf", "ndg", "ndh", "ndi",
    "ndl", "ndm", "ndn", "ndo", "ndp", "ndq", "ndr", "nds", "ndt", "ndu",
    "ndv", "ndw", "ndy", "ndz", "nea", "neb", "nec", "ned", "nee", "nef",
    "neg", "neh", "nei", "nel", "nem", "nen", "neo", "nep", "neq", "ner",
    "nes", "net", "neu", "nev", "new", "nex", "nez", "nfa", "nfe", "nfl",
    "nfo", "nfr", "nfu", "nga", "ngb", "ngc", "ngd", "nge", "ngf", "ngg",
    "ngh", "ngi", "ngl", "ngm", "ngn", "ngo", "ngp", "ngq", "ngr", "ngs",
    "ngt", "ngu", "ngv", "ngw", "ngz", "nha", "nhe", "nhi", "nho", "nhy",
    "nic", "nig", "nim", "nin", "nio", "nis", "nit", "nla", "nle", "nlu",
    "nma", "nme", "nmi", "nmo", "nna", "nne", "nno", "nob", "nol", "nom",
    "non", "nop", "nor", "nos", "nov", "npa", "npe", "nph", "npi", "npl",
    "npo", "npr", "nps", "npu", "nqu", "nre", "nro", "nsa", "nsc", "nse",
    "nsi", "nsk", "nsl", "nsm", "nso", "nst", "nsu", "nsw", "nsy", "nta",
    "ntb", "ntc", "ntd", "nte", "ntf", "ntg", "nth", "nti", "ntl", "ntm",
    "ntn", "nto", "ntp", "ntq", "ntr", "nts", "ntt", "ntu", "ntv", "ntw",
    "ntz", "nua", "nul", "nun", "nve", "nvi", "nvo", "nwa", "nwe", "nwi",
    "nwo", "nya", "nyb", "nyc", "nyd", "nye", "nyf", "nyg", "nyh", "nyi",
    "nyl", "nym", "nyn", "nyo", "nyp", "nyq", "nyr", "nys", "nyt", "nyu",
    "nyv", "nyw", "nyz", "nze", 
    "oab", "oac", "oad", "oae", "oal", "oam", "oan", "oap", "oat", "obl",
    "obo", "obs", "obu", "oca", "oce", "och", "oci", "ocl", "oco", "ocr",
    "ocu", "ode", "odi", "odl", "odo", "ody", "oel", "oem", "oen", "oep",
    "oev", "oex", "ofa", "ofb", "ofc", "ofd", "ofe", "off", "ofg", "ofh",
    "ofi", "ofl", "ofm", "ofn", "ofo", "ofp", "ofq", "ofr", "ofs", "oft",
    "ofu", "ofv", "ofw", "ofz", "ogo", "ogr", "ogu", "oha", "ohe", "ohi",
    "oho", "ohy", "oid", "oim", "oin", "ois", "oke", "ola", "olb", "olc",
    "old", "ole", "olf", "olg", "olh", "oli", "oll", "olm", "oln", "olo",
    "olp", "olq", "olr", "ols", "olt", "olu", "olv", "olw", "olz", "oma",
    "omb", "omc", "omd", "ome", "omf", "omg", "omh", "omi", "oml", "omm",
    "omn", "omo", "omp", "omq", "omr", "oms", "omt", "omu", "omv", "omw",
    "omz", "ona", "onb", "onc", "ond", "one", "onf", "ong", "onh", "oni",
    "onl", "onm", "onn", "ono", "onp", "onq", "onr", "ons", "ont", "onu",
    "onv", "onw", "ony", "onz", "oob", "ood", "oof", "oop", "opa", "ope",
    "oph", "opi", "opl", "opo", "opp", "opr", "ops", "opu", "oqu", "ora",
    "orc", "ord", "ore", "ork", "orm", "oro", "orp", "orr", "ors", "ort",
    "osa", "osc", "ose", "osi", "osk", "osl", "osm", "oso", "ost", "osu",
    "osw", "osy", "ota", "ote", "oth", "oto", "otr", "ott", "otu", "oug",
    "oul", "oun", "ous", "out", "ova", "ove", "ovi", "ovo", "owa", "owb",
    "owc", "owd", "owe", "owf", "owg", "owh", "owi", "owl", "owm", "own",
    "owo", "owp", "owq", "owr", "ows", "owt", "owu", "owv", "oww", "owz",
    "oxa", "oxb", "oxc", "oxd", "oxe", "oxf", "oxg", "oxh", "oxi", "oxl",
    "oxm", "oxn", "oxo", "oxp", "oxq", "oxr", "oxs", "oxt", "oxu", "oxv",
    "oxw", "oxz", "oya", "oyb", "oyc", "oyd", "oye", "oyf", "oyg", "oyh",
    "oyi", "oyl", "oym", "oyn", "oyo", "oyp", "oyq", "oyr", "oys", "oyt",
    "oyu", "oyv", "oyw", "oyz", "oze", 
    "pab", "pac", "pad", "pae", "pal", "pam", "pan", "pap", "paq", "par",
    "pat", "pbl", "pbo", "pbu", "pca", "pce", "pch", "pci", "pcl", "pco",
    "pcr", "pcu", "pde", "pdi", "pdo", "pdy", "pea", "peb", "pec", "ped",
    "pee", "pef", "peg", "peh", "pei", "pel", "pem", "pen", "peo", "pep",
    "peq", "per", "pes", "pet", "peu", "pev", "pew", "pex", "pez", "pfa",
    "pfe", "pfl", "pfo", "pfr", "pfu", "pgo", "pgr", "pha", "phe", "phi",
    "pho", "phy", "pic", "pid", "pig", "pim", "pin", "pit", "pla", "ple",
    "plu", "pma", "pme", "pmi", "pmo", "pne", "pno", "pob", "poi", "pok",
    "pop", "por", "pos", "pot", "ppa", "ppe", "pph", "ppi", "ppl", "ppo",
    "ppr", "pps", "ppu", "pqu", "pre", "pri", "pro", "psa", "psc", "pse",
    "psk", "psl", "psm", "pso", "pst", "psu", "psw", "psy", "pta", "pte",
    "pth", "pti", "pto", "ptr", "ptu", "pul", "pun", "pur", "put", "pve",
    "pvi", "pvo", "pwa", "pwe", "pwi", "pwo", "pze", 
    "que", "quo", 
    "raa", "rab", "rac", "rad", "rae", "raf", "rag", "rah", "rai", "ral",
    "ram", "ran", "rao", "rap", "raq", "rar", "ras", "rat", "rau", "rav",
    "raw", "raz", "rbl", "rbo", "rbu", "rca", "rce", "rch", "rci", "rcl",
    "rco", "rcr", "rcu", "rda", "rdb", "rdc", "rdd", "rde", "rdf", "rdg",
    "rdh", "rdi", "rdl", "rdm", "rdn", "rdo", "rdp", "rdq", "rdr", "rds",
    "rdt", "rdu", "rdv", "rdw", "rdy", "rdz", "rea", "reb", "rec", "red",
    "ree", "ref", "reg", "reh", "rei", "rel", "rem", "ren", "reo", "rep",
    "req", "rer", "res", "ret", "reu", "rev", "rew", "rex", "rez", "rfa",
    "rfe", "rfl", "rfo", "rfr", "rfu", "rge", "rgo", "rgr", "rha", "rhe",
    "rhi", "rho", "rhy", "ric", "rid", "rim", "rin", "rit", "riv", "rka",
    "rkb", "rkc", "rkd", "rke", "rkf", "rkg", "rkh", "rki", "rkl", "rkm",
    "rkn", "rko", "rkp", "rkq", "rkr", "rks", "rkt", "rku", "rkv", "rkw",
    "rkz", "rla", "rlb", "rlc", "rld", "rle", "rlf", "rlg", "rlh", "rli",
    "rll", "rlm", "rln", "rlo", "rlp", "rlq", "rlr", "rls", "rlt", "rlu",
    "rlv", "rlw", "rlz", "rma", "rme", "rmi", "rmo", "rna", "rnb", "rnc",
    "rnd", "rne", "rnf", "rng", "rnh", "rni", "rnl", "rnm", "rnn", "rno",
    "rnp", "rnq", "rnr", "rns", "rnt", "rnu", "rnv", "rnw", "rnz", "rob",
    "roc", "rod", "rof", "rog", "roh", "roi", "ron", "rop", "ros", "rot",
    "rov", "rox", "rpa", "rpe", "rph", "rpi", "rpl", "rpo", "rpr", "rps",
    "rpu", "rqu", "rre", "rri", "rro", "rry", "rsa", "rsc", "rse", "rsh",
    "rsk", "rsl", "rsm", "rso", "rst", "rsu", "rsw", "rsy", "rta", "rtb",
    "rtc", "rtd", "rte", "rtf", "rtg", "rth", "rti", "rtl", "rtm", "rtn",
    "rto", "rtp", "rtq", "rtr", "rts", "rtt", "rtu", "rtv", "rtw", "rty",
    "rtz", "rue", "rul", "run", "rup", "rve", "rvi", "rvo", "rwa", "rwe",
    "rwi", "rwo", "rya", "ryb", "ryc", "ryd", "rye", "ryf", "ryg", "ryh",
    "ryi", "ryl", "rym", "ryn", "ryo", "ryp", "ryq", "ryr", "rys", "ryt",
    "ryu", "ryv", "ryw", "ryz", "rze", 
    "sab", "sac", "sad", "sae", "sal", "sam", "san", "sap", "sat", "sbl",
    "sbo", "sbu", "sca", "sce", "sch", "sci", "scl", "sco", "scr", "scu",
    "sde", "sdi", "sdo", "sdy", "sea", "seb", "sec", "sed", "see", "sef",
    "seg", "seh", "sei", "sel", "sem", "sen", "seo", "sep", "seq", "ser",
    "ses", "set", "seu", "sev", "sew", "sex", "sez", "sfa", "sfe", "sfl",
    "sfo", "sfr", "sfu", "sgo", "sgr", "sha", "shb", "shc", "shd", "she",
    "shf", "shg", "shh", "shi", "shl", "shm", "shn", "sho", "shp", "shq",
    "shr", "shs", "sht", "shu", "shv", "shw", "shy", "shz", "sib", "sic",
    "sim", "sin", "sio", "sis", "ske", "sla", "sle", "slu", "sly", "sma",
    "smb", "smc", "smd", "sme", "smf", "smg", "smh", "smi", "sml", "smm",
    "smn", "smo", "smp", "smq", "smr", "sms", "smt", "smu", "smv", "smw",
    "smz", "sne", "sno", "sob", "sof", "sol", "son", "sop", "spa", "spe",
    "sph", "spi", "spl", "spo", "spr", "sps", "spu", "squ", "sre", "sro",
    "sru", "ssa", "ssb", "ssc", "ssd", "sse", "ssf", "ssg", "ssh", "ssi",
    "ssk", "ssl", "ssm", "ssn", "sso", "ssp", "ssq", "ssr", "sss", "sst",
    "ssu", "ssv", "ssw", "ssy", "ssz", "sta", "stb", "stc", "std", "ste",
    "stf", "stg", "sth", "sti", "stl", "stm", "stn", "sto", "stp", "stq",
    "str", "sts", "stt", "stu", "stv", "stw", "stz", "sua", "sul", "sun",
    "sur", "sus", "sve", "svi", "svo", "swa", "swe", "swi", "swo", "syc",
    "sym", "sys", "sze", 
    "tab", "tac", "tad", "tae", "tag", "tai", "tal", "tam", "tan", "tap",
    "tat", "tbl", "tbo", "tbu", "tca", "tce", "tch", "tci", "tcl", "tco",
    "tcr", "tcu", "tde", "tdi", "tdo", "tdy", "tea", "teb", "tec", "ted",
    "tee", "tef", "teg", "teh", "tei", "tel", "tem", "ten", "teo", "tep",
    "teq", "ter", "tes", "tet", "teu", "tev", "tew", "tex", "tez", "tfa",
    "tfe", "tfl", "tfo", "tfr", "tfu", "tgo", "tgr", "tha", "thb", "thc",
    "thd", "the", "thf", "thg", "thh", "thi", "thl", "thm", "thn", "tho",
    "thp", "thq", "thr", "ths", "tht", "thu", "thv", "thw", "thy", "thz",
    "tic", "tig", "til", "tim", "tin", "tio", "tip", "tiv", "tla", "tle",
    "tlu", "tma", "tme", "tmi", "tmo", "tne", "tno", "tob", "toc", "tog",
    "tom", "top", "tor", "tou", "tpa", "tpe", "tph", "tpi", "tpl", "tpo",
    "tpr", "tps", "tpu", "tqu", "tra", "tre", "tri", "tro", "tsa", "tsc",
    "tse", "tsk", "tsl", "tsm", "tso", "tst", "tsu", "tsw", "tsy", "tta",
    "tte", "tth", "tti", "tto", "ttr", "ttu", "tub", "tul", "tun", "tur",
    "tve", "tvi", "tvo", "twa", "twe", "twi", "two", "tya", "tyb", "tyc",
    "tyd", "tye", "tyf", "tyg", "tyh", "tyi", "tyl", "tym", "tyn", "tyo",
    "typ", "tyq", "tyr", "tys", "tyt", "tyu", "tyv", "tyw", "tyz", "tze", 
    "uag", "ual", "uat", "ube", "uci", "uck", "ucr", "uct", "uea", "ueb",
    "uec", "ued", "uee", "uef", "ueg", "ueh", "uei", "uel", "uem", "uen",
    "ueo", "uep", "ueq", "uer", "ues", "uet", "ueu", "uev", "uew", "uez",
    "ugh", "uit", "ulo", "ult", "umv", "und", "uni", "uot", "upi", "upt",
    "urc", "ure", "urf", "uri", "urr", "usa", "usb", "usc", "usd", "use",
    "usf", "usg", "ush", "usi", "usl", "usm", "usn", "uso", "usp", "usq",
    "usr", "uss", "ust", "usu", "usv", "usw", "usz", "uta", "utb", "utc",
    "utd", "ute", "utf", "utg", "uth", "uti", "utl", "utm", "utn", "uto",
    "utp", "utq", "utr", "uts", "utt", "utu", "utv", "utw", "utz", 
    "vac", "val", "vat", "vea", "veb", "vec", "ved", "vee", "vef", "veg",
    "veh", "vei", "vel", "vem", "ven", "veo", "vep", "veq", "ver", "ves",
    "vet", "veu", "vev", "vew", "vez", "via", "vid", "vis", "vit", "voc",
    "vol", "vot", 
    "wab", "wac", "wad", "wae", "waf", "wal", "wam", "wan", "wap", "war",
    "wat", "wbl", "wbo", "wbu", "wca", "wce", "wch", "wci", "wcl", "wco",
    "wcr", "wcu", "wde", "wdi", "wdo", "wdy", "wea", "wel", "wem", "wen",
    "wep", "wev", "wex", "wfa", "wfe", "wfl", "wfo", "wfr", "wfu", "wgo",
    "wgr", "wha", "whe", "whi", "who", "why", "wim", "win", "wir", "wit",
    "wla", "wle", "wlu", "wma", "wme", "wmi", "wmo", "wne", "wno", "wob",
    "wop", "wor", "wpa", "wpe", "wph", "wpi", "wpl", "wpo", "wpr", "wps",
    "wpu", "wqu", "wre", "wro", "wsa", "wsc", "wse", "wsk", "wsl", "wsm",
    "wso", "wst", "wsu", "wsw", "wsy", "wta", "wte", "wth", "wto", "wtr",
    "wtu", "wul", "wun", "wve", "wvi", "wvo", "wwa", "wwe", "wwi", "wwo",
    "wze", 
    "xab", "xac", "xad", "xae", "xal", "xam", "xan", "xap", "xat", "xbl",
    "xbo", "xbu", "xca", "xce", "xch", "xci", "xcl", "xco", "xcr", "xcu",
    "xde", "xdi", "xdo", "xdy", "xel", "xem", "xen", "xep", "xev", "xex",
    "xfa", "xfe", "xfl", "xfo", "xfr", "xfu", "xgo", "xgr", "xha", "xhe",
    "xhi", "xho", "xhy", "xim", "xin", "xla", "xle", "xlu", "xma", "xme",
    "xmi", "xmo", "xne", "xno", "xob", "xop", "xor", "xpa", "xpe", "xph",
    "xpi", "xpl", "xpo", "xpr", "xps", "xpu", "xqu", "xre", "xro", "xsa",
    "xsc", "xse", "xsk", "xsl", "xsm", "xso", "xst", "xsu", "xsw", "xsy",
    "xta", "xte", "xth", "xto", "xtr", "xtu", "xul", "xun", "xve", "xvi",
    "xvo", "xwa", "xwe", "xwi", "xwo", "xze", 
    "yab", "yac", "yad", "yae", "yal", "yam", "yan", "yap", "yat", "ybl",
    "ybo", "ybu", "yca", "yce", "ych", "yci", "ycl", "yco", "ycr", "ycu",
    "yde", "ydi", "ydo", "ydy", "yel", "yem", "yen", "yep", "yev", "yex",
    "yfa", "yfe", "yfl", "yfo", "yfr", "yfu", "ygo", "ygr", "yha", "yhe",
    "yhi", "yho", "yhy", "yim", "yin", "yla", "yle", "ylu", "yma", "yme",
    "ymi", "ymo", "ymp", "yna", "yne", "yno", "yob", "yop", "ypa", "ype",
    "yph", "ypi", "ypl", "ypo", "ypr", "yps", "ypt", "ypu", "yqu", "yre",
    "yro", "ysa", "ysc", "yse", "ysk", "ysl", "ysm", "yso", "yst", "ysu",
    "ysw", "ysy", "yta", "yte", "yth", "yto", "ytr", "ytu", "yul", "yun",
    "yve", "yvi", "yvo", "ywa", "ywe", "ywi", "ywo", "yze", 
    "zen", 
	};

const int threeLetterOffset[26] = {
	0, // a
	199, // b
	218, // c
	429, // d
	587, // e
	811, // f
	915, // g
	1055, // h
	1213, // i
	-1, // j
	1390, // k
	1503, // l
	1689, // m
	1807, // n
	2011, // o
	2266, // p
	2393, // q
	2395, // r
	2660, // s
	2853, // t
	3023, // u
	3112, // v
	3144, // w
	3245, // x
	3341, // y
	3439, // z
	};

const int threeLetterOffsetEnd[26] = {
	198,
	217,
	428,
	586,
	810,
	914,
	1054,
	1212,
	1389,
	-1,
	1502,
	1688,
	1806,
	2010,
	2265,
	2392,
	2394,
	2659,
	2852,
	3022,
	3111,
	3143,
	3244,
	3340,
	3438,
	3440,
	};


